[package]
name = "MyOrdinalsLoan"
version = "0.1.0"
upgrade_policy = "compatible"


[addresses]
my_ordinalsloan = "0xb07f6898631da46c024a6e6726c11fb874ba7d958fad6e58edc4007681714448"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }


[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

